import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  // === Font Sizes ===
  text_10: { fontSize: 10 },
  text_12: { fontSize: 12 },
  text_14: { fontSize: 14 },
  text_16: { fontSize: 16 },
  text_18: { fontSize: 18 },
  text_20: { fontSize: 20 },
  text_24: { fontSize: 24 },
  text_28: { fontSize: 28 },
  text_30: { fontSize: 30 },
  text_32: { fontSize: 32 },

  // === Font Weights ===
  font_100: { fontWeight: "100" },
  font_200: { fontWeight: "200" },
  font_300: { fontWeight: "300" },
  font_400: { fontWeight: "400" },
  font_500: { fontWeight: "500" },
  font_600: { fontWeight: "600" },
  font_700: { fontWeight: "700" },
  font_800: { fontWeight: "800" },
  font_900: { fontWeight: "900" },

  // === Widths ===
  w_1: { width: 1 },
  w_2: { width: 2 },
  w_3: { width: 3 },
  w_4: { width: 4 },
  w_5: { width: 5 },
  w_6: { width: 6 },
  w_7: { width: 7 },
  w_8: { width: 8 },
  w_9: { width: 9 },
  w_10: { width: 10 },
  w_12: { width: 12 },
  w_14: { width: 14 },
  w_16: { width: 16 },
  w_18: { width: 18 },
  w_20: { width: 20 },
  w_24: { width: 24 },
  w_26: { width: 26 },
  w_28: { width: 28 },
  w_32: { width: 32 },
  w_34: { width: 34 },
  w_36: { width: 36 },
  w_38: { width: 38 },
  w_40: { width: 40 },
  w_48: { width: 48 },
  w_50: { width: 50 },
  w_full: { width: "100%" },

  // === Heights ===
  h_1: { height: 1 },
  h_2: { height: 2 },
  h_3: { height: 3 },
  h_4: { height: 4 },
  h_5: { height: 5 },
  h_6: { height: 6 },
  h_7: { height: 7 },
  h_8: { height: 8 },
  h_9: { height: 9 },
  h_10: { height: 10 },
  h_12: { height: 12 },
  h_14: { height: 14 },
  h_16: { height: 16 },
  h_18: { height: 18 },
  h_20: { height: 20 },
  h_24: { height: 24 },
  h_26: { height: 26 },
  h_28: { height: 28 },
  h_32: { height: 32 },
  h_34: { height: 34 },
  h_36: { height: 36 },
  h_38: { height: 38 },
  h_40: { height: 40 },
  h_48: { height: 48 },
  h_50: { height: 50 },
  h_full: { height: "100%" },

  // === Margin ===
  m_0: { margin: 0 },
  m_1: { margin: 1 },
  m_2: { margin: 2 },
  m_4: { margin: 4 },
  m_6: { margin: 6 },
  m_8: { margin: 8 },
  m_10: { margin: 10 },
  m_12: { margin: 12 },
  m_14: { margin: 14 },
  m_16: { margin: 16 },
  m_18: { margin: 18 },
  m_20: { margin: 20 },

  // Margin Horizontal
  mx_0: { marginHorizontal: 0 },
  mx_2: { marginHorizontal: 2 },
  mx_4: { marginHorizontal: 4 },
  mx_6: { marginHorizontal: 6 },
  mx_8: { marginHorizontal: 8 },
  mx_10: { marginHorizontal: 10 },
  mx_12: { marginHorizontal: 12 },
  mx_14: { marginHorizontal: 14 },
  mx_16: { marginHorizontal: 16 },
  mx_18: { marginHorizontal: 18 },
  mx_20: { marginHorizontal: 20 },

  // Margin Vertical
  my_0: { marginVertical: 0 },
  my_2: { marginVertical: 2 },
  my_4: { marginVertical: 4 },
  my_6: { marginVertical: 6 },
  my_8: { marginVertical: 8 },
  my_10: { marginVertical: 10 },
  my_12: { marginVertical: 12 },
  my_14: { marginVertical: 14 },
  my_16: { marginVertical: 16 },
  my_18: { marginVertical: 18 },
  my_20: { marginVertical: 20 },

  // === Padding ===
  p_0: { padding: 0 },
  p_1: { padding: 1 },
  p_2: { padding: 2 },
  p_4: { padding: 4 },
  p_8: { padding: 8 },
  p_10: { padding: 10 },
  p_12: { padding: 12 },
  p_14: { padding: 14 },
  p_16: { padding: 16 },
  p_20: { padding: 20 },
  p_24: { padding: 24 },
  p_32: { padding: 32 },
  p_40: { padding: 40 },
  p_50: { padding: 50 },

  // Padding Horizontal
  px_0: { paddingHorizontal: 0 },
  px_2: { paddingHorizontal: 2 },
  px_4: { paddingHorizontal: 4 },
  px_8: { paddingHorizontal: 8 },
  px_10: { paddingHorizontal: 10 },
  px_12: { paddingHorizontal: 12 },
  px_14: { paddingHorizontal: 14 },
  px_16: { paddingHorizontal: 16 },
  px_18: { paddingHorizontal: 18 },
  px_20: { paddingHorizontal: 20 },

  // Padding Vertical
  py_0: { paddingVertical: 0 },
  py_2: { paddingVertical: 2 },
  py_4: { paddingVertical: 4 },
  py_8: { paddingVertical: 8 },
  py_10: { paddingVertical: 10 },
  py_12: { paddingVertical: 12 },
  py_14: { paddingVertical: 14 },
  py_16: { paddingVertical: 16 },
  py_18: { paddingVertical: 18 },
  py_20: { paddingVertical: 20 },

  ml_0: { marginLeft: 0 },
  ml_1: { marginLeft: 1 },
  ml_2: { marginLeft: 2 },
  ml_4: { marginLeft: 4 },
  ml_8: { marginLeft: 8 },
  ml_10: { marginLeft: 10 },
  ml_12: { marginLeft: 12 },
  ml_14: { marginLeft: 14 },
  ml_16: { marginLeft: 16 },
  ml_20: { marginLeft: 20 },
  ml_24: { marginLeft: 24 },
  ml_32: { marginLeft: 32 },
  ml_40: { marginLeft: 40 },
  ml_50: { marginLeft: 50 },

  // Margin Right
  mr_0: { marginRight: 0 },
  mr_1: { marginRight: 1 },
  mr_2: { marginRight: 2 },
  mr_4: { marginRight: 4 },
  mr_8: { marginRight: 8 },
  mr_10: { marginRight: 10 },
  mr_12: { marginRight: 12 },
  mr_14: { marginRight: 14 },
  mr_16: { marginRight: 16 },
  mr_20: { marginRight: 20 },
  mr_24: { marginRight: 24 },
  mr_32: { marginRight: 32 },
  mr_40: { marginRight: 40 },
  mr_50: { marginRight: 50 },

  // Margin Top
  mt_0: { marginTop: 0 },
  mt_1: { marginTop: 1 },
  mt_2: { marginTop: 2 },
  mt_4: { marginTop: 4 },
  mt_8: { marginTop: 8 },
  mt_10: { marginTop: 10 },
  mt_12: { marginTop: 12 },
  mt_14: { marginTop: 14 },
  mt_16: { marginTop: 16 },
  mt_20: { marginTop: 20 },
  mt_24: { marginTop: 24 },
  mt_32: { marginTop: 32 },
  mt_40: { marginTop: 40 },
  mt_50: { marginTop: 50 },

  // Margin Bottom
  mb_0: { marginBottom: 0 },
  mb_1: { marginBottom: 1 },
  mb_2: { marginBottom: 2 },
  mb_4: { marginBottom: 4 },
  mb_8: { marginBottom: 8 },
  mb_10: { marginBottom: 10 },
  mb_12: { marginBottom: 12 },
  mb_14: { marginBottom: 14 },
  mb_16: { marginBottom: 16 },
  mb_20: { marginBottom: 20 },
  mb_24: { marginBottom: 24 },
  mb_32: { marginBottom: 32 },
  mb_40: { marginBottom: 40 },
  mb_50: { marginBottom: 50 },

  // === Flex ===
  flex: { flex: 1 },
  flex_row: { flexDirection: "row" },
  flex_col: { flexDirection: "column" },
  items_center: { alignItems: "center" },
  items_start: { alignItems: "flex-start" },
  items_end: { alignItems: "flex-end" },
  justify_center: { justifyContent: "center" },
  justify_start: { justifyContent: "flex-start" },
  justify_end: { justifyContent: "flex-end" },
  justify_between: { justifyContent: "space-between" },
  justify_around: { justifyContent: "space-around" },
  justify_evenly: { justifyContent: "space-evenly" },

  // === Background Colors ===
  bg_white: { backgroundColor: "white" },
  bg_black: { backgroundColor: "black" },
  bg_gray: { backgroundColor: "gray" },
  bg_red: { backgroundColor: "red" },
  bg_blue: { backgroundColor: "blue" },
  bg_green: { backgroundColor: "green" },

  //   Border Radius
  rounded: { borderRadius: 4 },
  rounded_sm: { borderRadius: 8 },
  rounded_md: { borderRadius: 12 },
  rounded_lg: { borderRadius: 16 },
  rounded_xl: { borderRadius: 20 },
  rounded_2xl: { borderRadius: 24 },
  rounded_3xl: { borderRadius: 32 },
  rounded_full: { borderRadius: 9999 },

  //   Border Width
  border: { borderWidth: 1 },
  border_2: { borderWidth: 2 },
  border_4: { borderWidth: 4 },
  border_8: { borderWidth: 8 },

  //  Text Color
  text_white: { color: "white" },
  text_black: { color: "black" },
  text_gray: { color: "gray" },
  text_red: { color: "red" },
  text_blue: { color: "blue" },
  text_green: { color: "green" },
});

export const merge = (classes) => {
  return classes.split(" ").reduce((acc, c) => ({ ...acc, ...styles[c] }), {});
};

export default styles;
